#!/usr/bin/env bash
### terra-bot -- run the price feed bot
### Usage: terra bot --api-key <KEY>
### Main price bot
### Needs --api-key <KEY>

set -e

export ETH_RPC_URL=https://mainnet.infura.io

[[ $ETH_FROM ]] || terra --bad-usage "$0"
ETH_FROM=$(seth --to-address "$ETH_FROM")

if ! [[ $TERRA_API_KEY ]]; then
  echo >&2 "Generating API key for $ETH_FROM"
  key=$(terra join "$ETH_FROM")
  export TERRA_API_KEY=$key
  echo >&2 "Key: $key"
fi

function feed {
  price=$(setzer price "$1")
  now=$(date +%s)

  hash=$(terra pack "$(seth --to-wei "$price" eth)" "$now")
  echo >&2 "Pair:  $1_usd"
  echo >&2 "Price: $price"
  echo >&2 "Now:   $now"
  echo >&2 "Hash:  $hash"

  sig=$(ethsign msg --from "$ETH_FROM" --data "$hash" --passphrase-file "$ETH_PASSWORD")

  echo >&2 "Sig:   $sig"
  echo >&2 ""

  terra send "$sig" "$price" "$now" "$1_usd"
}

while true; do
  feed eth
  feed mkr
  echo "Waiting 60 seconds"
  sleep 60
done
