#!/usr/bin/env node
/*
### terra-send -- send data to network
### Usage: terra send <args>
*/

var key = process.env.TERRA_API_KEY || null
var from = process.env.ETH_FROM || null;
var sig = process.argv[2] || null;
var price = process.argv[3] || null;
var now = process.argv[4] || null;

if (!key || !from || !sig || !price || !now) {
  try {
    require('child_process').execSync('terra --bad-usage ' + process.argv[1])
  } catch(e) {
    process.exit(1)
  }
}

var stream = require('getstream');
var client = stream.connect('5mypkddvbjdd', null, '33873');
var user = client.feed('user', from, key);

user.addActivity({
  actor: from,
  verb: 'post',
  data: {
    from: from,
    price: price,
    now: now,
    sig: sig
  }
})
