#!/usr/bin/env bash
### terra-bot -- run the price feed bot
### Usage: terra bot --api-key <KEY>
### Main price bot
### Needs --api-key <KEY>

set -e

[[ $TERRA_API_KEY && $ETH_FROM ]] || terra --bad-usage "$0"

ETH_FROM=$(seth --to-address "$ETH_FROM")

price=$(setzer price eth)
now=$(date +%s)

hash=$(terra pack "$(seth --to-wei "$price" eth)" "$now")
echo >&2 "Price: $price"
echo >&2 "Now:   $now"
echo >&2 "Hash:  $hash"

sig=$(ethsign msg --from "$ETH_FROM" --data "$hash")
printf "\\n"
echo "$sig"
