#!/usr/bin/env bash
cat <<.
terra 0.1.1
License: GNU GPL version 3 or later <https://gnu.org/licenses/gpl>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.
