#!/usr/bin/env bash
### terra-bot -- run the price feed bot
### Usage: terra bot --api-key <KEY>
### Main price bot
### Needs --api-key <KEY>

set -e

[[ $TERRA_API_KEY && $ETH_FROM ]] || terra --bad-usage "$0"

ETH_FROM=$(seth --to-address "$ETH_FROM")

price=$(setzer price eth)
timestamp=$(date +%s)

hash=$(terra pack "$(seth --to-wei "$price" eth)" "$timestamp")
echo "$hash"

sig=$(ethsign msg --from "$ETH_FROM" --data "$hash" --passphrase-file "$ETH_PASSWORD")
printf "\\n"
echo "$sig"
