#!/usr/bin/env bash
### terra-join -- get API key to join oracle network
### Usage: terra join <address>

set -e

[[ $1 ]] || terra --bad-usage "$0"

address=$(seth --to-address "$1")
now=$(date +%s)

export ETH_RPC_URL=https://mainnet.infura.io
hash=$(seth keccak "$now")
echo >&2 "Sending hashed message"
sig=$(ethsign msg --from "$ETH_FROM" --data "$hash" --passphrase-file "$ETH_PASSWORD")

key=$(curl -sS -d "address=$address&now=$now&sig=$sig" -X POST "https://dai-service.makerdao.com/token")
# key=$(curl -sS -d "address=$address&now=$now&sig=$sig" -X POST "http://localhost:3000/token")

[[ ${#key} = 27 ]] || { echo >&2 "Something went wrong. Could not get API key."; exit 1; }

echo >&2 "Verified."
echo "$key"
