#!/usr/bin/env bash
### terra-pack -- return hash of <price> (wei) and <timestamp> (seconds)
### Usage: terra pack <price> <timestamp>
### price must be in wei, timestamp in seconds
### example: terra pack 1500000000000000000000 1518296924

[[ $# = 2 ]] || terra --bad-usage "$0"

wad=$(seth --to-word "$1")
zzz=$(seth --to-word "$2")

seth keccak 0x"$wad$zzz"
