#!/usr/bin/env bash
### terra-verify -- verify signed message
### Usage: terra verify <hash> <address> <price> <timestamp>
### fails if <address> did not sign <hash> with <price> and <timestamp>
set -e

price=$1
now=$2
sig=$3

hash=$(terra pack "$(seth --to-wei "$price" eth)" "$now")

echo >&2 "Hash:    $hash"

address=$(ethsign recover --data "$hash" --sig "$sig")

echo "Address: $address"